# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFormyfirsttest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_formyfirsttest(self):
    self.driver.get("https://formy-project.herokuapp.com/autocomplete")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.ID, "autocomplete").click()
    self.driver.find_element(By.ID, "autocomplete").click()
    self.driver.find_element(By.ID, "autocomplete").send_keys("chernivci")
    self.driver.find_element(By.CSS_SELECTOR, ".dismissButton").click()
    self.driver.find_element(By.ID, "street_number").click()
    self.driver.find_element(By.ID, "street_number").send_keys("ruska 271")
    self.driver.find_element(By.ID, "route").click()
    self.driver.find_element(By.ID, "route").send_keys("svobody 19")
    self.driver.find_element(By.ID, "locality").click()
    self.driver.find_element(By.ID, "locality").send_keys("chernivtsi")
    self.driver.find_element(By.ID, "administrative_area_level_1").click()
    self.driver.find_element(By.ID, "administrative_area_level_1").send_keys("ukraine")
    self.driver.find_element(By.ID, "postal_code").click()
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.CSS_SELECTOR, ".container").click()
    self.driver.find_element(By.ID, "postal_code").click()
    self.driver.find_element(By.ID, "postal_code").send_keys("some zit")
    self.driver.find_element(By.ID, "country").click()
    self.driver.find_element(By.ID, "country").send_keys("this is my country")
    self.driver.find_element(By.CSS_SELECTOR, "h1").click()
  
